version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: assignment-mysql
    environment:
      MYSQL_DATABASE: assignment
      MYSQL_USER: assignment
      MYSQL_PASSWORD: assignment
      MYSQL_ROOT_PASSWORD: rootpassword
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD | grep 'mysqld is alive' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  redis:
    image: redis:7-alpine
    container_name: assignment-redis
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  wiremock:
    image: wiremock/wiremock:3.5.2
    container_name: assignment-wiremock
    ports:
      - "8089:8080"
    command:
      - --verbose

  sonarqube:
    image: sonarqube:10.7.0-community
    container_name: assignment-sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

  app:
    build:
      context: .
    container_name: assignment-app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8081:8080"

volumes:
  db-data:
  redis-data:
